name: ml-labs-updated
channels:
  - anaconda
  - anaconda-fusion
  - defaults
  - conda-forge
  - ankurankan
dependencies:
  - python
  - jupyter
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - pandas
  - pymc
  - jupyter
  - ipykernel
  - scikit-learn
  - pgmpy
  - opt_einsum
  - pip:
      - pyro-ppl

