name: ml-labs
channels:
  - anaconda
  - anaconda-fusion
  - defaults
  - conda-forge
  - ankurankan
dependencies:
  - python=3.9
  - jupyter
  - numpy<1.26
  - scipy<1.13
  - seaborn
  - matplotlib
  - pandas
  - pymc>=5
  - jupyter
  - ipykernel
  - scikit-learn
  - pgmpy
  - opt_einsum

